# Training the generator with multiple properties
control:
  restart: False
  history_file: "biasing_history.csv"
  max_iter: 1000
  comment: "ReLeaSE Generator Test"
  verbosity: 0
  smi_file: "/home/seabra/work/li/elion_dev/bleeding/elion/example_smiles.smi"
generator:
  name: "ReLeaSE"
  author: "Isayev"
  initial_state: "/home/seabra/work/li/hitopt/hitopt/generator/release/checkpoints/generator/checkpoint_biggest_rnn"
  batch_size: 200
  # Start with celecoxib
  seed_smi: "Cc1ccc(-c2cc(C(F)(F)F)nn2-c2ccc(S(N)(=O)=O)cc2)cc1"
        
properties:
  Prop1:
    prop_class: 'secondary'
    rew_weight: 0.3
  Prop2: 
    prop_class: 'secondary'
    rew_weight: 0.7
    rew_class: 'soft'
    rew_acc: 0.05
  SAScore:
    prop_class: 'primary'
  QEDScore:
    prop_class: 'primary'
  VinaScore: 
    prop_class: 'primary'
    optimize: True
    threshold_init: -8.0
    threshold_limit: -12.0
    threshold_step: -0.01

